Update static CSVs (remove duplicated IE613 antenna positions)
brentjens/lofar-antenna-positions pull request #13
Opened 2020-11-11 13:27 UTC by David-McKenna

Hi Michiel,

This PR goes alongside #12 to show the differences in the local CSVs after regenerating them from the current state of the ASTRON git. As I noted in #12,

- This removes duplicated IE613 antenna
- The ordering of the core HBA entries phase centre entries has been modified slightly

Cheers,
David

2020-11-11 13:34 UTC, David-McKenna commented
I suspect the build is failing, and these extra antenna were added, as a focus to get tests compiling after our LBA array definition was adjusted by 6cm ( https://git.astron.nl/ro/lofar/-/commit/b34203f6896e2c0da1d04ca029b185e3a9dfa929 )

I'll update the test cases shortly.

2020-11-16 15:46 UTC, brentjens requested changes
Hi David,

thank you very much for this work! Could you please regenerate the file such that coordinates are rounded to the closest mm?
Thank you so much!
- Michiel

2020-11-16 16:14 UTC, David-McKenna commented
Hey Michiel,

I've updated #12 to ensure that it will only print the phase centres to millimetre precision, updated the test cases again to account for the slight change, and pushed the resulting changes to the branch here as well. Do you want me to squash all the commits?

Cheers,
David

2020-11-16 17:39 UTC, brentjens approved these changes

2020-11-16 17:39 UTC, merged